services:
  - type: web
    name: hmitlc-backend-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MAILERLITE_API_KEY
        sync: false
      - key: SYSTEM_RESET_SECRET
        sync: false
      - key: NODE_ENV
        value: production
